### ISSUE TITLE
R430 Missing CPU Temp Error. CPU0/CPU1 Swap Typo?

### ISSUE THREAD

**Issue by greggsymington** [White-Raven/PowerEdge-shutup#6]
Thanks for publishing this script!
I may have a bit of an edge case issue with this script on a single CPU R430 running Unraid. While running the log shows it has gone into "Ambient fan mode - Delta mode" saying there was no CPU temp found.  Running the ipmitool ... sdr type temperature command it showed my CPU0 as 0Eh. Switching CPUID0 from 0Fh to 0Eh and CPUID1 from 0Eh to 0Fh was the solution for me. Just wanted to share in case anyone else had the same problem.

**Comment by White-Raven** [comment]
Good catch!
Actually it was indeed reversed, even for my own server (R720), but since I run dual CPU, I never noticed I did that oopsie.
Since the script couldn't find CPU0, it thought there was no CPU reading at all and thus used the Ambient fall back.

I will swap the IDs in the provided script and they will be in the correct order in next revisions too, and in the sometime™ rewrite I started months ago.
